"""empty message

Revision ID: 02f9eeae3ed0
Revises: f251499d5574
Create Date: 2020-04-02 12:11:41.029743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02f9eeae3ed0'
down_revision = 'f251499d5574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_message', sa.Column('is_show', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_message', 'is_show')
    # ### end Alembic commands ###
