"""empty message

Revision ID: 3ba241dae628
Revises: 563c67fdd6d2
Create Date: 2020-04-07 16:00:48.512622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba241dae628'
down_revision = '563c67fdd6d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'create_time')
    # ### end Alembic commands ###
