"""empty message

Revision ID: 563c67fdd6d2
Revises: 8a41e8eee7f6
Create Date: 2020-04-07 15:46:20.016835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563c67fdd6d2'
down_revision = '8a41e8eee7f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('process', sa.String(length=50), nullable=True))
    op.add_column('reservation', sa.Column('work_teacher', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reservation', 'teacher', ['work_teacher'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'work_teacher')
    op.drop_column('reservation', 'process')
    # ### end Alembic commands ###
