"""empty message

Revision ID: 5c7190b03bef
Revises: 1bd893a98048
Create Date: 2020-04-02 14:59:40.226662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c7190b03bef'
down_revision = '1bd893a98048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('name', sa.String(length=25), nullable=True))
    op.drop_column('teacher', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('username', mysql.VARCHAR(length=25), nullable=True))
    op.drop_column('teacher', 'name')
    # ### end Alembic commands ###
