"""empty message

Revision ID: 71c99deff5b1
Revises: d0ec43b1c878
Create Date: 2020-04-02 16:25:04.167052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c99deff5b1'
down_revision = 'd0ec43b1c878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('is_use', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'is_use')
    # ### end Alembic commands ###
