"""empty message

Revision ID: 8a41e8eee7f6
Revises: e1d5e28c6da4
Create Date: 2020-04-05 16:14:49.008961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a41e8eee7f6'
down_revision = 'e1d5e28c6da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_question', sa.Column('test_content', sa.TEXT(), nullable=True))
    op.add_column('test_question', sa.Column('test_time', sa.Date(), nullable=True))
    op.add_column('test_question', sa.Column('test_title', sa.String(length=255), nullable=True))
    op.drop_column('test_question', 'text_content')
    op.drop_column('test_question', 'text_title')
    op.drop_column('test_question', 'text_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_question', sa.Column('text_time', sa.DATE(), nullable=True))
    op.add_column('test_question', sa.Column('text_title', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('test_question', sa.Column('text_content', mysql.TEXT(), nullable=True))
    op.drop_column('test_question', 'test_title')
    op.drop_column('test_question', 'test_time')
    op.drop_column('test_question', 'test_content')
    # ### end Alembic commands ###
