"""empty message

Revision ID: a277934d4ed6
Revises: f2c39e21e9c3
Create Date: 2020-04-03 16:20:02.090986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a277934d4ed6'
down_revision = 'f2c39e21e9c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('name', sa.String(length=25), nullable=True))
    op.drop_column('admin', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('username', mysql.VARCHAR(length=25), nullable=True))
    op.drop_column('admin', 'name')
    # ### end Alembic commands ###
