"""empty message

Revision ID: abc8d3dac069
Revises: d780c311e380
Create Date: 2020-03-31 15:41:39.411250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc8d3dac069'
down_revision = 'd780c311e380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_message', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('user_message', sa.Column('message', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_message', 'message')
    op.drop_column('user_message', 'create_time')
    # ### end Alembic commands ###
