"""empty message

Revision ID: c67d5ae6759a
Revises: acf2384fc3e4
Create Date: 2020-04-05 15:43:34.244445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67d5ae6759a'
down_revision = 'acf2384fc3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('email', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'email')
    # ### end Alembic commands ###
