"""empty message

Revision ID: ccf5f02626e2
Revises: 24bef015d1a1
Create Date: 2020-03-31 19:56:47.524294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ccf5f02626e2'
down_revision = '24bef015d1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_ibfk_1', 'admin', type_='foreignkey')
    op.drop_column('admin', 'is_success')
    op.drop_column('admin', 's_id')
    op.drop_column('admin', 'is_use')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('is_use', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('admin', sa.Column('s_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('admin', sa.Column('is_success', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_foreign_key('admin_ibfk_1', 'admin', 'user', ['s_id'], ['id'])
    # ### end Alembic commands ###
