"""empty message

Revision ID: d09ac67ba02c
Revises: cae239ad25d2
Create Date: 2020-03-31 20:13:36.893073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd09ac67ba02c'
down_revision = 'cae239ad25d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'article_intro')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_intro', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
