"""empty message

Revision ID: d0ec43b1c878
Revises: f963b88c6b77
Create Date: 2020-04-02 16:14:37.016719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0ec43b1c878'
down_revision = 'f963b88c6b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'phone',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'phone',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    # ### end Alembic commands ###
