"""empty message

Revision ID: dadec936aeee
Revises: 02ce3b05285e
Create Date: 2020-04-02 16:12:48.768892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dadec936aeee'
down_revision = '02ce3b05285e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'QQ',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=12),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'QQ',
               existing_type=sa.String(length=12),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    # ### end Alembic commands ###
