"""empty message

Revision ID: f2c39e21e9c3
Revises: ca7e444e2f6b
Create Date: 2020-04-03 15:32:32.568981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2c39e21e9c3'
down_revision = 'ca7e444e2f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('is_use', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'is_use')
    # ### end Alembic commands ###
