"""empty message

Revision ID: f3e82e5eb9fd
Revises: f061704b0071
Create Date: 2020-04-02 12:14:36.230563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e82e5eb9fd'
down_revision = 'f061704b0071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_message', sa.Column('is_replay', sa.Integer(), nullable=True))
    op.add_column('user_message', sa.Column('replay', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_message', 'replay')
    op.drop_column('user_message', 'is_replay')
    # ### end Alembic commands ###
