"""empty message

Revision ID: f963b88c6b77
Revises: 6135d6bfac7f
Create Date: 2020-04-02 16:13:54.759563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f963b88c6b77'
down_revision = '6135d6bfac7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'Wechat',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservation', 'Wechat',
               existing_type=sa.String(length=25),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    # ### end Alembic commands ###
